startDelaySeconds: 0
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
rules:
  # Metrics related to Producers
  - pattern: "kafka.producer<type=producer-metrics, client-id=([^:]+)><>([^:]+)"
    name: "kafka_producer_metrics_$2"
    labels:
      client: "$1"
  # Metrics related to Producers and topics
  - pattern: "kafka.producer<type=producer-topic-metrics, client-id=([^:]+), topic=([^:]+)><>([^:]+)"
    name: "kafka_producer_topic_metrics_$3"
    labels:
      client: "$1"
      topic: "$2"
